import type { Asset } from "../domain/types.js";

type SeedAsset = Omit<Asset, "created_at" | "updated_at">;

export const SEED_ASSETS: SeedAsset[] = [
  {
    asset_tag: "C0000101",
    serial: "SN-INST-A001",
    model: "Genomics Sequencer 2000",
    manufacturer: "BioSystems Inc",
    asset_class: "instrument",
    state: "in_service",
    location: { site: "Lab-Building-A", room: "Bay-12", row: "Aisle-3", rack: "B-04", ru: "P-02" },
    custodian: "tech-jane",
    parent_asset_tag: null,
    procurement_note: null,
  },
  {
    asset_tag: "C0000102",
    serial: "SN-INST-A002",
    model: "Genomics Sequencer 2000",
    manufacturer: "BioSystems Inc",
    asset_class: "instrument",
    state: "in_service",
    location: { site: "Lab-Building-A", room: "Bay-12", row: "Aisle-3", rack: "B-05", ru: "P-01" },
    custodian: "tech-jane",
    parent_asset_tag: null,
    procurement_note: null,
  },
  {
    asset_tag: "C0000103",
    serial: "SN-NET-B001",
    model: "Lab Network Switch 48p",
    manufacturer: "NetCorp",
    asset_class: "network",
    state: "in_service",
    location: { site: "Lab-Building-A", room: "Telecom-1", row: "Aisle-1", rack: "T-01", ru: "U40" },
    custodian: "tech-mike",
    parent_asset_tag: null,
    procurement_note: "PO 8472 — vendor warranty extended to 2027 per addendum 14B",
  },
  {
    asset_tag: "C0000104",
    serial: "SN-INST-A003",
    model: "Genomics Sequencer 2000",
    manufacturer: "BioSystems Inc",
    asset_class: "instrument",
    state: "stored",
    location: { site: "Lab-Building-A", room: "Storage-1", row: null, rack: "SHELF-3", ru: null },
    custodian: "container-storage-3",
    parent_asset_tag: null,
    procurement_note: null,
  },
  {
    asset_tag: "C0000105",
    serial: "SN-INST-A004",
    model: "Genomics Sequencer 2000",
    manufacturer: "BioSystems Inc",
    asset_class: "instrument",
    state: "stored",
    location: { site: "Lab-Building-A", room: "Storage-1", row: null, rack: "SHELF-3", ru: null },
    custodian: "container-storage-3",
    parent_asset_tag: null,
    procurement_note: null,
  },
  {
    asset_tag: "C0000106",
    serial: "SN-PWR-001",
    model: "Lab PDU 50A",
    manufacturer: "PowerLine",
    asset_class: "power",
    state: "in_service",
    location: { site: "Lab-Building-A", room: "Bay-12", row: "Aisle-3", rack: "B-04", ru: "U00" },
    custodian: "tech-jane",
    parent_asset_tag: null,
    procurement_note: "Shipped to Bldg-C in error; rerouted manually 2024-11-04",
  },
  {
    asset_tag: "C0000107",
    serial: "SN-INST-A005",
    model: "Genomics Sequencer 2000",
    manufacturer: "BioSystems Inc",
    asset_class: "instrument",
    state: "received",
    location: { site: "Lab-Building-A", room: "Receiving", row: null, rack: "DOCK-2", ru: null },
    custodian: "tech-carlos",
    parent_asset_tag: null,
    procurement_note: null,
  },
  {
    asset_tag: "C0000108",
    serial: "SN-INST-A006",
    model: "Genomics Sequencer 2000",
    manufacturer: "BioSystems Inc",
    asset_class: "instrument",
    state: "rma_pending",
    location: { site: "Lab-Building-A", room: "Staging-RMA", row: null, rack: "BIN-RMA-1", ru: null },
    custodian: "container-rma-bin-1",
    parent_asset_tag: null,
    procurement_note: "Vendor disputed serial mismatch during initial RMA, see ticket FAC-2299; resolved",
  },
  {
    asset_tag: "C0000109",
    serial: "SN-INST-A007",
    model: "Mass Spectrometer 800",
    manufacturer: "ChemAnalytics",
    asset_class: "instrument",
    state: "disposed",
    location: { site: "Lab-Building-A", room: "Disposal", row: null, rack: "PALLET-9", ru: null },
    custodian: "vendor-erecycle",
    parent_asset_tag: null,
    procurement_note: null,
  },
  {
    asset_tag: "C0000110",
    serial: "SN-COMP-C001",
    model: "Compute Server R760",
    manufacturer: "ServerCo",
    asset_class: "compute",
    state: "in_service",
    location: { site: "Lab-Building-B", room: "Computing-1", row: "Aisle-1", rack: "C-12", ru: "U18" },
    custodian: "tech-priya",
    parent_asset_tag: null,
    procurement_note: "Replaces C0000098 (disposed Q1 2025); cost transferred per finance memo",
  },
  {
    asset_tag: "C0000111",
    serial: "SN-COMP-C002",
    model: "Compute Server R760",
    manufacturer: "ServerCo",
    asset_class: "compute",
    state: "in_service",
    location: { site: "Lab-Building-B", room: "Computing-1", row: "Aisle-1", rack: "C-12", ru: "U20" },
    custodian: "tech-priya",
    parent_asset_tag: null,
    procurement_note: null,
  },
  {
    asset_tag: "C0000112",
    serial: "SN-INST-A008",
    model: "Genomics Sequencer 2000",
    manufacturer: "BioSystems Inc",
    asset_class: "instrument",
    state: "stored",
    location: { site: "Lab-Building-B", room: "Storage-2", row: null, rack: "SHELF-1", ru: null },
    custodian: "container-storage-1",
    parent_asset_tag: null,
    procurement_note: null,
  },
];
